import { useState, useContext } from "react";
import { useSelector, useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
import { clearCart } from "../redux/cartSlice";
import API from "../api/axios";

const Checkout = () => {
  const { user } = useContext(AuthContext);
  const cartItems = useSelector((state) => state.cart.cartItems) || [];
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const [address, setAddress] = useState({
    fullname: "",
    street: "",
    city: "",
    state: "",
    postalCode: "",
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const totalPrice = cartItems.reduce(
    (acc, item) => acc + Number(item.price) * item.qty,
    0,
  );

  // const handlePayment = async () => {
  //   setIsProcessing(true);

  //   if (typeof window.Razorpay === "undefined") {
  //     console.warn(
  //       "Razorpay script not loaded in DOM. Diverting to Student Bypass Mode...",
  //     );
  //     return bypassPayment();
  //   }
  //   try {
  //     // 1. Create order on your backend server first
  //     // Razorpay requires the exact amount in paise (Rupees * 100) on the backend!
  //     const orderRouteResponse = await API.post("/api/payment/order", {
  //       amount: totalPrice,
  //     }).catch((err) => {
  //       console.warn(
  //         "Backend order creation rejected. Falling back to Student Bypass Mode...",
  //         err,
  //       );
  //       return null;
  //     });

  //     // If backend payment controller is unconfigured, auto-fallback to bypass
  //     if (!orderRouteResponse || !orderRouteResponse.data) {
  //       return bypassPayment();
  //     }

  //     const orderData = orderRouteResponse.data;

  //     // 2. Configure Razorpay Standard Checkout Test Mode options
  //     const options = {
  //       // Reads your public test key ID from Vite env files or drops back to standard dummy string
  //       key: import.meta.env.VITE_RAZORPAY_KEY_ID || "rzp_test_dummykey123",
  //       amount: orderData.amount, // Amount returned from backend (already in paise)
  //       currency: orderData.currency || "INR",
  //       name: "FirstCart Tech",
  //       description: "Razorpay Sandbox Test Mode Transaction",
  //       order_id: orderData.id, // Absolute tracking order ID generated by your backend Razorpay instance

  //       // Success callback trigger fired instantly when test payment succeeds
  //       handler: async function (paymentResponse) {
  //         try {
  //           setIsProcessing(true);

  //           // Verify payment signatures on your Express backend server
  //           const verifyRes = await API.post("/api/payment/verify", {
  //             razorpay_order_id: paymentResponse.razorpay_order_id,
  //             razorpay_payment_id: paymentResponse.razorpay_payment_id,
  //             razorpay_signature: paymentResponse.razorpay_signature,
  //           });

  //           if (
  //             verifyRes.data?.status === "success" ||
  //             verifyRes.status === 200
  //           ) {
  //             // Create true MongoDB order document record inside your collection cluster
  //             const saveOrderRes = await API.post("/api/orders", {
  //               items: cartItems.map((item) => ({
  //                 productId: item.productId || item._id,
  //                 qty: item.qty,
  //                 price: item.price.toString(),
  //               })),
  //               totalAmount: totalPrice,
  //               address,
  //               paymentId: paymentResponse.razorpay_payment_id,
  //             });

  //             if (saveOrderRes.status === 201 || saveOrderRes.status === 200) {
  //               dispatch(clearCart());
  //               navigate("/ordersuccess");
  //             } else {
  //               alert(
  //                 "Payment captured, but order saving failed on the database server.",
  //               );
  //             }
  //           } else {
  //             alert("Payment signature verification handshake failed.");
  //           }
  //         } catch (err) {
  //           console.error("Verification processing error:", err);
  //           alert("Error connecting to backend order verification shards.");
  //         } finally {
  //           setIsProcessing(false);
  //         }
  //       },
  //       prefill: {
  //         name: address.fullname,
  //         email: user?.email || "testuser@example.com",
  //         contact: "9999999999",
  //       },
  //       theme: {
  //         color: "#2563eb", // FirstCart Theme Blue
  //       },
  //       modal: {
  //         ondismiss: function () {
  //           setIsProcessing(false);
  //           console.log("Checkout modal dismissed by test operator.");
  //         },
  //       },
  //     };

  //     const rzp1 = new window.Razorpay(options);
  //     rzp1.open();
  //   } catch (error) {
  //     console.error("Razorpay Execution Crash:", error);
  //     alert(
  //       "Payment processing pipeline exception error. Check terminal stack trace records.",
  //     );
  //   } finally {
  //     if (!window.Razorpay) {
  //       setIsProcessing(false);
  //     }
  //   }
  // };

  // Student Sandbox Auto-Bypass fallback routine
  
  const bypassPayment = async () => {
    try {
      const saveOrderRes = await API.post("/api/orders", {
        items: cartItems.map((item) => ({
          productId: item.productId || item._id,
          qty: item.qty,
          price: item.price.toString(),
        })),
        totalAmount: totalPrice,
        address,
        paymentId: "bypass_test_txn_" + Date.now(),
      });

      if (saveOrderRes.status === 201 || saveOrderRes.status === 200) {
        dispatch(clearCart());
        navigate("/ordersuccess");
      } else {
        alert("Bypass checkout database write operation failed.");
      }
    } catch (err) {
      console.error(err);
      alert(
        err.response?.data?.message ||
          "Error executing student fallback sequence.",
      );
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!user) {
      alert("Please log in to your account profile first to checkout.");
      navigate('/login');
      return;
    }
    if (cartItems.length === 0) {
      alert("Your shopping basket is empty.");
      navigate('/shop');
      return;
    }
    
    bypassPayment(); 
  };

  return (
    <div className="bg-zinc-950 min-h-screen text-zinc-100 px-4 py-12 sm:px-6 lg:px-8 relative overflow-hidden">
      {/* Ambient glassmorphic decorative glow filters grid */}
      <div className="absolute top-1/4 left-1/4 w-100 h-100 bg-blue-500/5 rounded-full blur-3xl pointer-events-none"></div>

      <div className="max-w-4xl mx-auto relative z-10">
        {/* HEADER BRANDING BANNER */}
        <div className="border-b border-zinc-900/80 pb-6 mb-10">
          <h1 className="text-3xl font-black text-white tracking-tight">
            Checkout Gate
          </h1>
          <p className="text-xs text-zinc-500 mt-1.5 uppercase tracking-wider font-semibold">
            Configure shipping parameters and authorize{" "}
            <span className="text-blue-400 font-bold">Razorpay Test Mode</span>{" "}
            nodes.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
          {/* LEFT COLUMN: SHIPMENT DETAILS CAPTURE ADDRESS FORM */}
          <form
            onSubmit={handleSubmit}
            className="lg:col-span-2 bg-zinc-900/40 backdrop-blur-md border border-zinc-900/80 p-6 sm:p-8 rounded-2xl space-y-5 shadow-xl"
          >
            <h3 className="text-sm font-bold text-white tracking-widest uppercase border-b border-zinc-800/60 pb-3 mb-2">
              Shipping Coordinates
            </h3>

            <div className="space-y-4">
              <input
                type="text"
                placeholder="Receiver Full Name"
                required
                value={address.fullname}
                onChange={(e) =>
                  setAddress({ ...address, fullname: e.target.value })
                }
                className="dark-input-field py-3 bg-zinc-950/40 focus:bg-zinc-950"
                disabled={isProcessing}
              />
              <input
                type="text"
                placeholder="Street Address, Flat/Apt Number"
                required
                value={address.street}
                onChange={(e) =>
                  setAddress({ ...address, street: e.target.value })
                }
                className="dark-input-field py-3 bg-zinc-950/40 focus:bg-zinc-950"
                disabled={isProcessing}
              />
              <div className="grid grid-cols-2 gap-4">
                <input
                  type="text"
                  placeholder="City"
                  required
                  value={address.city}
                  onChange={(e) =>
                    setAddress({ ...address, city: e.target.value })
                  }
                  className="dark-input-field py-3 bg-zinc-950/40 focus:bg-zinc-950"
                  disabled={isProcessing}
                />
                <input
                  type="text"
                  placeholder="State (e.g. Maharashtra)"
                  required
                  value={address.state}
                  onChange={(e) =>
                    setAddress({ ...address, state: e.target.value })
                  }
                  className="dark-input-field py-3 bg-zinc-950/40 focus:bg-zinc-950"
                  disabled={isProcessing}
                />
              </div>
              <input
                type="text"
                placeholder="Postal PIN Code"
                required
                value={address.postalCode}
                onChange={(e) =>
                  setAddress({ ...address, postalCode: e.target.value })
                }
                className="dark-input-field py-3 bg-zinc-950/40 focus:bg-zinc-950"
                disabled={isProcessing}
              />
            </div>

            <button
              type="submit"
              className="hidden"
              id="hidden-submit-trigger"
            />
          </form>

          {/* RIGHT COLUMN: RECAP TRANSACTION BOX SUMMARY */}
          <div className="bg-zinc-900/50 backdrop-blur-md border border-zinc-900 rounded-2xl p-6 space-y-6 shadow-2xl sticky top-28">
            <h3 className="text-xs font-bold text-white tracking-widest uppercase border-b border-zinc-800 pb-3">
              Payment Summary
            </h3>

            <div className="space-y-4 text-sm font-medium">
              <div className="flex justify-between text-zinc-400">
                <span>Items Subtotal</span>
                <span className="font-bold text-zinc-200">
                  ₹{totalPrice.toLocaleString("en-IN")}
                </span>
              </div>
              <div className="flex justify-between text-zinc-400">
                <span>Priority Logistics</span>
                <span className="text-teal-400 font-bold uppercase text-xs tracking-wider bg-teal-950/30 border border-teal-900/30 px-2 py-0.5 rounded-md">
                  Free
                </span>
              </div>
              <div className="pt-4 border-t border-zinc-800 flex justify-between items-baseline">
                <span className="font-bold text-zinc-300">Grand Total</span>
                <span className="text-2xl font-black bg-linear-to-r from-blue-400 to-indigo-400 bg-clip-text text-transparent tracking-tight">
                  ₹{totalPrice.toLocaleString("en-IN")}
                </span>
              </div>
            </div>

            {/* PAY NOW TRIGGER BUTTON */}
            <button
              onClick={() =>
                document.getElementById("hidden-submit-trigger").click()
              }
              disabled={isProcessing}
              className="w-full bg-linear-to-r from-blue-600 to-indigo-600 hover:from-indigo-600 hover:to-blue-600 text-white font-bold py-4 rounded-xl transition-all shadow-xl shadow-blue-500/10 text-sm transform hover:-translate-y-0.5 text-center flex items-center justify-center gap-2 focus:outline-none focus:ring-2 focus:ring-blue-500/50 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
            >
              {isProcessing ? (
                <>
                  <span className="animate-spin inline-block h-4 w-4 border-2 border-white border-t-transparent rounded-full"></span>
                  Contacting Gateway Secure Shards...
                </>
              ) : (
                <>
                  <span>🔒</span> Pay via Razorpay Test Mode
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Checkout;
